name: test
on: [push, pull_request]
jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Variables
        run: |
          echo "runner_arch=$(uname -m)" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: docker context create builders
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          endpoint: builders
      - name: Cache Docker Layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: "${{ runner.os }}-${{ env.runner_arch }}-buildx-cpp-${{ github.sha }}"
          restore-keys: "${{ runner.os }}-${{ env.runner_arch }}-buildx-cpp-"
      - run: mkdir -p ./output/
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: test/linux.Dockerfile
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          outputs: type=local,dest=./output/
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          # token: ${{ secrets.CODECOV_TOKEN }}
          name: codecov
          env_vars: OS
          fail_ci_if_error: true
          directory: ./output/
          files: ./jcu_unio_coverage.xml
          flags: unittests
          path_to_write_report: ./output/codecov_report.txt
          verbose: true
  windows-build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "CMake Cache"
        run: |
          mkdir "C:\\build"
          cd "C:\\build"
          ls "${{ github.workspace }}"
          & 'C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7\Tools\Launch-VsDevShell.ps1'
          cmake "${{ github.workspace }}"
      - name: "CMake Build"
        run: |
          cd "C:\\build"
          cmake --build . --config RelWithDebInfo
#      - name: Set up Docker Context for Buildx
#        id: buildx-context
#        run: docker context create builders
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
#        with:
#          version: latest
#          endpoint: builders
#      - name: Cache Docker Layers
#        uses: actions/cache@v2
#        with:
#          path: /tmp/.buildx-cache
#          key: "${{ runner.os }}-amd64-buildx-cpp-${{ github.sha }}"
#          restore-keys: "${{ runner.os }}-amd64-buildx-cpp-"
#      - name: Build
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          file: test/windows.Dockerfile
#          push: false
#          tags: local/temp:latest
#          cache-from: type=local,src=/tmp/.buildx-cache
#          cache-to: type=local,dest=/tmp/.buildx-cache-new
#      - name: Move cache
#        run: |
#          rm -rf /tmp/.buildx-cache
#          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
